---
- name: Configure EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a test HTML file
      copy:
        dest: /var/www/html/index.html
        content: "<html><body><h1>Hello from Ansible</h1></body></html>"
