name: Terraform and Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Terraform and Ansible'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0

    - name: 'Terraform Init'
      run: | 
        cd terraform
        terraform init

    - name: 'Terraform Apply'
      run: | 
        cd terraform
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: 'Install Ansible'
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: 'Run Ansible Playbook'
      run: |
        ansible-playbook -i 'ec2-instance-public-ip,' --private-key /path/to/your/private-key.pem ansible-playbooks/site.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
