name: Terraform and Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Terraform and Ansible'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0

    - name: 'Terraform Init'
      run: | 
        cd terraform
        terraform init

    - name: 'Terraform Apply'
      id: tf_apply
      run: | 
        cd terraform
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: 'Install Ansible'
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: 'Check Ansible Playbook Path'
      run: |
        if [ ! -f ansible-playbooks/site.yml ]; then
          echo "Ansible playbook not found!"
          exit 1
        fi

    - name: 'Get EC2 Public IP'
      id: get_ip
      run: |
        cd terraform
        echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

    - name: 'Run Ansible Playbook'
      run: |
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i "${{ env.EC2_PUBLIC_IP }}," --private-key /path/to/your/private-key.pem ansible-playbooks/site.yml
      env:
        EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}
